plugins {
    id "com.android.application"
}

android {
    namespace "dev.mirror.repurpose"
    compileSdk 35

    defaultConfig {
        applicationId "dev.mirror.repurpose"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "0.3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    def media3Version = "1.9.0"

    implementation "androidx.media3:media3-exoplayer:${media3Version}"
    implementation "androidx.media3:media3-exoplayer-dash:${media3Version}"
    implementation "androidx.media3:media3-exoplayer-hls:${media3Version}"
    implementation "androidx.media3:media3-exoplayer-rtsp:${media3Version}"
    implementation "androidx.media3:media3-ui:${media3Version}"
    compileOnly "androidx.annotation:annotation:1.6.0"
    implementation "org.nanohttpd:nanohttpd:2.3.1"

    testImplementation "junit:junit:4.13.2"
}
