package dev.mirror.repurpose;

import android.content.Context;
import android.util.Log;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/**
 * Upcoming UTC-offset changes for every IANA zone, generated by
 * tools/zone_offsets.py. It stands in for the time-zone rules this firmware
 * lacks until a paired browser supplies fresher ones.
 */
final class ZoneOffsetTable {
    static final String ASSET_NAME = "zone-offsets.json";

    private static final String TAG = "ZoneOffsetTable";
    private static final long MINUTE_MS = 60_000L;
    private static volatile ZoneOffsetTable instance;

    private final Map<String, UtcOffsetTimeline> zones;
    private final String tzdata;

    private ZoneOffsetTable(Map<String, UtcOffsetTimeline> zones, String tzdata) {
        this.zones = zones;
        this.tzdata = tzdata;
    }

    static ZoneOffsetTable getInstance(Context context) {
        ZoneOffsetTable table = instance;
        if (table == null) {
            synchronized (ZoneOffsetTable.class) {
                table = instance;
                if (table == null) {
                    table = load(context.getApplicationContext());
                    instance = table;
                }
            }
        }
        return table;
    }

    static ZoneOffsetTable empty() {
        return new ZoneOffsetTable(new HashMap<>(), "");
    }

    static ZoneOffsetTable parse(String json) throws JSONException {
        JSONObject document = new JSONObject(json);
        if (document.getInt("version") != 1) {
            throw new JSONException("Unsupported zone table version");
        }
        JSONArray rules = document.getJSONArray("rules");
        UtcOffsetTimeline[] timelines = new UtcOffsetTimeline[rules.length()];
        for (int index = 0; index < rules.length(); index++) {
            timelines[index] = timeline(rules.getJSONArray(index));
        }
        JSONObject names = document.getJSONObject("zones");
        Map<String, UtcOffsetTimeline> zones = new HashMap<>();
        Iterator<String> keys = names.keys();
        while (keys.hasNext()) {
            String name = keys.next();
            int rule = names.getInt(name);
            if (rule < 0 || rule >= timelines.length) {
                throw new JSONException("Zone refers to a missing rule: " + name);
            }
            zones.put(name, timelines[rule]);
        }
        return new ZoneOffsetTable(zones, document.optString("tzdata", ""));
    }

    /** The zone's offsets, or null when the table does not know the zone. */
    UtcOffsetTimeline timelineFor(String zoneId) {
        return zoneId == null ? null : zones.get(zoneId);
    }

    String tzdata() {
        return tzdata;
    }

    int size() {
        return zones.size();
    }

    private static UtcOffsetTimeline timeline(JSONArray rule) throws JSONException {
        int base = rule.getInt(0);
        JSONArray changes = rule.getJSONArray(1);
        long[] at = new long[changes.length()];
        int[] offsets = new int[changes.length()];
        long previous = 0L;
        for (int index = 0; index < changes.length(); index++) {
            JSONArray change = changes.getJSONArray(index);
            at[index] = change.getLong(0) * MINUTE_MS;
            offsets[index] = change.getInt(1);
            if (at[index] <= previous || !UtcOffsetTimeline.validOffset(offsets[index])) {
                throw new JSONException("Invalid zone offset change");
            }
            previous = at[index];
        }
        if (!UtcOffsetTimeline.validOffset(base)) {
            throw new JSONException("Invalid zone offset");
        }
        return new UtcOffsetTimeline(base, at, offsets);
    }

    private static ZoneOffsetTable load(Context context) {
        try (InputStream input = context.getAssets().open(ASSET_NAME);
                ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            byte[] buffer = new byte[8192];
            int count;
            while ((count = input.read(buffer)) != -1) {
                output.write(buffer, 0, count);
            }
            return parse(new String(output.toByteArray(), StandardCharsets.UTF_8));
        } catch (IOException | JSONException error) {
            // Without the table the clock keeps its saved offset, as before.
            Log.e(TAG, "Unable to load the bundled zone table", error);
            return empty();
        }
    }
}
